#!/bin/sh

###########
#         #
#  bspwm  #
#         #
###########

# start/restart
start() {
    killall $1
    $@ &
}

# startup
start sxhkd
start feh --bg-scale /mnt/Portable/Pictures/Wallpapers/leaves2.jpg
start picom
start tint2
start dunst

xsetroot -cursor_name left_ptr
pactl set-sink-volume @DEFAULT_SINK@ 50%

# desktops
bspc monitor -d I II III IV V VI VII VIII IX X

# border
bspc config focused_border_color "#999999"
bspc config normal_border_color  "#333333"

# windows
bspc config border_width          1
bspc config split_ratio           0.5
bspc config window_gap            4

# monocle
bspc config single_monocle        true
bspc config gapless_monocle       true
bspc config borderless_monocle    true

# control
bspc config focus_follows_pointer true
bspc config pointer_motion_interval 4

# preselect
bspc config presel_feedback_color \#66a2ff
